/** Migrate + seed the functional test DB. Usage: node testing/functional/prepare.mjs */
import { writeFileSync, existsSync, copyFileSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import pg from 'pg'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const envPath = resolve(root, 'testing/functional/.env.testing')
const examplePath = resolve(root, 'testing/functional/.env.testing.example')

function ensureEnvFile() {
  if (process.env.CI || process.env.FUNCTIONAL_FORCE_ENV === '1') {
    const url =
      process.env.DATABASE_URL ||
      'postgresql://crm_test:crm_test_local_only@127.0.0.1:5432/brains_crm_test'
    const body = `# Generated by testing/functional/prepare.mjs for CI
DATABASE_URL=${url}
DB_URL_DEV=${url}
DB_SSL=false
ALLOW_ACTIVITY_SEED=1
PORT=4000
JWT_SECRET=${process.env.JWT_SECRET || 'testing-jwt-secret-not-for-prod'}
ALLOWED_EMAIL_DOMAIN=${process.env.ALLOWED_EMAIL_DOMAIN || 'convobrains.com'}
CORS_ORIGINS=http://127.0.0.1:5173,http://localhost:5173,http://localhost:4000
`
    writeFileSync(envPath, body)
    console.log(`Wrote ${envPath}`)
    return
  }

  if (!existsSync(envPath)) {
    copyFileSync(examplePath, envPath)
    console.log(`Copied example → ${envPath}`)
  }
}

function loadEnvFile(path) {
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const t = line.trim()
    if (!t || t.startsWith('#')) continue
    const i = t.indexOf('=')
    if (i < 0) continue
    const key = t.slice(0, i).trim()
    let val = t.slice(i + 1).trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    process.env[key] = val
  }
}

async function migrateWithPg() {
  const url = process.env.DATABASE_URL
  if (!url) throw new Error('DATABASE_URL missing after env load')
  const sql = readFileSync(resolve(root, 'sql/schema.sql'), 'utf8')
  const client = new pg.Client({ connectionString: url, ssl: false })
  await client.connect()
  try {
    await client.query(sql)
    console.log('Schema applied via node-pg')
  } finally {
    await client.end()
  }
}

function runNode(script) {
  const r = spawnSync(process.execPath, [script], {
    cwd: root,
    stdio: 'inherit',
    env: process.env,
  })
  if (r.status !== 0) process.exit(r.status ?? 1)
}

ensureEnvFile()
loadEnvFile(envPath)

await migrateWithPg()
runNode(resolve(root, 'testing/functional/seed-users.mjs'))
runNode(resolve(root, 'testing/functional/seed-crm.mjs'))
runNode(resolve(root, 'testing/functional/seed-activity.mjs'))
console.log('Functional DB prepared.')
